# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userName',
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('uname', models.CharField(max_length=12)),
                ('upassword', models.CharField(max_length=32)),
                ('ulast_time_password', models.CharField(max_length=32)),
                ('uregistration_time', models.DateTimeField()),
                ('ulast_time_login_time', models.DateTimeField()),
                ('ulast_time_login_addr', models.CharField(max_length=32)),
            ],
        ),
    ]
