# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_traveler', '0003_auto_20171117_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-uregistration_time',)},
        ),
        migrations.AddField(
            model_name='user',
            name='uuser_email',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ulast_time_login_addr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ulast_time_login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uregistration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
